/* global document, window, getComputedStyle */
const assert = require('node:assert/strict')
const fs = require('node:fs')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE)

;(async () => {
  const browser = await chromium.launch({ executablePath: process.env.BROWSER_EXECUTABLE, headless: true, args: ['--enable-unsafe-swiftshader'] })
  try {
    for (const width of [1280, 1536]) {
      const page = await browser.newPage({ viewport: { width, height: 900 } })
      const errors = []
      page.on('pageerror', error => errors.push(error.message))
      await page.route('**/api/auth/session', route => route.fulfill({ json: { seller: null } }))
      await page.route(/https:\/\/fonts\.(googleapis|gstatic)\.com\//, route => route.abort())
      await page.goto('http://localhost:3100/home', { waitUntil: 'domcontentloaded', timeout: 120000 })
      const nav = page.locator('[data-slot="sidebar-body"]')
      const pane = page.locator('[data-slot="sidebar"] main')
      const link = name => nav.getByRole('link', { name, exact: true })
      const child = name => nav.getByRole('button', { name, exact: true })
      const pin = child('Keep expanded')
      const settle = () => page.waitForTimeout(350)
      const capture = async name => {
        const session = await page.context().newCDPSession(page)
        const shot = await session.send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })
        fs.writeFileSync(`${process.env.TEMP}/home-sidebar-${width}-${name}.png`, Buffer.from(shot.data, 'base64'))
        await session.detach()
      }
      await nav.waitFor()
      await settle()
      await page.locator('[data-home-ambient] canvas[data-rendered="true"]').waitFor()
      assert.equal(await page.locator('[data-slot="home-sidebar-demo"]').evaluate(e => getComputedStyle(e).backgroundColor), 'rgb(22, 13, 35)')
      assert.deepEqual(await nav.locator('a[href^="#"]').allTextContents(), ['Profile', 'Listings', 'Messages', 'Settings'])
      assert.equal(await link('Profile').getAttribute('aria-current'), 'page')
      assert.equal(await link('Profile').getAttribute('aria-expanded'), 'true')
      assert.equal(await pane.locator('h2').textContent(), 'Profile')
      assert.equal(Math.round((await nav.boundingBox()).width), 64)
      assert.equal(await child('Overview').isVisible(), false)
      await capture('collapsed')
      const initialX = (await pane.boundingBox()).x
      await nav.hover()
      await page.waitForTimeout(60)
      assert((await nav.boundingBox()).width > 64 && (await nav.boundingBox()).width < 240)
      await settle()
      assert.equal(Math.round((await nav.boundingBox()).width), 240)
      assert.equal((await pane.boundingBox()).x, initialX)
      assert.equal(await child('Overview').count(), 0, 'Desktop Profile is one complete dashboard')
      assert.equal(await child('My Listings').isVisible(), false)
      assert.equal(await nav.evaluate(e => getComputedStyle(e).transitionDuration), '0.3s, 0.3s')
      assert.equal(await link('Profile').locator('span').last().evaluate(e => getComputedStyle(e).transitionDuration), '0.2s')
      await capture('profile')
      await link('Listings').click(); await settle()
      assert.equal(await child('Overview').isVisible(), false)
      for (const name of ['My Listings', 'Create Listing', 'Favorites']) assert.equal(await child(name).isVisible(), true)
      assert.equal(await pane.locator('h2').textContent(), 'My Listings')
      await child('Create Listing').click()
      assert.equal(await pane.locator('h2').textContent(), 'Create Listing')
      await child('Favorites').click()
      assert.equal(await child('Favorites').getAttribute('aria-current'), 'page')
      assert.equal(await link('Listings').getAttribute('aria-current'), 'page')
      assert.equal(await pane.locator('h2').textContent(), 'Favorites')
      await capture('favorites')
      await page.mouse.move(1000, 650)
      await pane.click(); await settle()
      assert.equal(Math.round((await nav.boundingBox()).width), 64)
      for (const name of ['Overview', 'My Listings', 'Create Listing', 'Favorites', 'Buying', 'Selling']) assert.equal(await child(name).isVisible(), false)
      await nav.hover(); await settle()
      assert.equal(await child('Favorites').getAttribute('aria-current'), 'page')
      assert.equal(await child('Favorites').isVisible(), true)
      await link('Profile').click(); await settle()
      assert.equal(await pane.locator('h2').textContent(), 'Profile')
      await link('Listings').click(); await settle()
      assert.equal(await child('My Listings').getAttribute('aria-current'), 'page')
      assert.equal(await pane.locator('h2').textContent(), 'My Listings')
      await link('Messages').click(); await settle()
      assert.equal(await child('Favorites').isVisible(), false)
      assert.equal(await child('Buying').isVisible(), true)
      assert.equal(await child('Selling').isVisible(), true)
      assert.equal(await child('Buying').getAttribute('aria-current'), 'page')
      assert.equal(await pane.locator('h2').textContent(), 'Messages')
      await child('Selling').click()
      assert.equal(await child('Selling').getAttribute('aria-current'), 'page')
      await capture('messages')
      await link('Settings').click(); await settle()
      assert.equal(await link('Settings').getAttribute('aria-current'), 'page')
      for (const name of ['Overview', 'My Listings', 'Create Listing', 'Favorites', 'Buying', 'Selling']) assert.equal(await child(name).isVisible(), false)
      assert.equal(await pane.locator('h2').textContent(), 'Settings')
      assert((await link('Settings').boundingBox()).y > (await link('Messages').boundingBox()).y + 300)
      assert((await pin.boundingBox()).y > (await link('Settings').boundingBox()).y)
      await capture('settings')
      await link('Listings').click(); await settle()
      assert.equal(await child('My Listings').getAttribute('aria-current'), 'page')
      assert.equal(await pane.locator('h2').textContent(), 'My Listings')
      await pin.click(); await pane.click(); await page.mouse.move(1000, 650); await settle()
      assert.equal(await pin.getAttribute('aria-pressed'), 'true')
      assert.equal(Math.round((await nav.boundingBox()).width), 240)
      assert.equal((await pane.boundingBox()).x, initialX + 176)
      await capture('pinned')
      await pin.click(); await pane.click(); await page.mouse.move(1000, 650); await settle()
      assert.equal(Math.round((await nav.boundingBox()).width), 64)
      await link('Profile').focus(); await page.keyboard.press('Tab'); await settle()
      assert.equal(Math.round((await nav.boundingBox()).width), 240)
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth))
      assert.equal(new URL(page.url()).pathname, '/home')
      assert.equal(new URL(page.url()).hash, '')
      assert.deepEqual(errors, [])
      console.log(`PASS ${width}: default Profile dashboard; Listings children; Favorites preserved across rail collapse; group re-entry resets to first child; Messages/Buying/Selling; bottom Settings; 64/240px hover/focus/pin; desktop ambient wave/dark separated surfaces; local state/no overflow/errors`)
      await page.close()
    }
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
