/* global location, history, document, window, getComputedStyle, requestAnimationFrame, performance */
const assert = require('node:assert/strict')
const fs = require('node:fs')
const {chromium} = require(process.env.PLAYWRIGHT_MODULE)
;(async () => {
 const browser = await chromium.launch({executablePath: process.env.BROWSER_EXECUTABLE, headless: true, args: ['--enable-unsafe-swiftshader']})
 try {
  for (const width of [1280,1536,390,430]) {
   const page = await browser.newPage({viewport:{width,height:900}})
   const errors=[]; page.on('pageerror',e=>errors.push(e.message))
   await page.route(/https:\/\/fonts\.(googleapis|gstatic)\.com\//,r=>r.abort())
   await page.route('**/api/auth/session',r=>r.fulfill({json:{seller:{id:'test',displayName:'Tester'}}}))
   await page.route('**/_next/data/**/listings.json*',async r=>{
    await new Promise(resolve=>setTimeout(resolve,1200))
    return r.fulfill({json:{pageProps:{listings:[], values:{status:'available',sort:'newest',search:'',category:'',condition:''},page:1,hasNextPage:false,error:null},__N_SSP:true}})
   })
   await page.goto('http://localhost:3100/listings',{waitUntil:'domcontentloaded',timeout:120000})
   await page.locator('[data-market-ready="true"]').waitFor({timeout:30000})
   await page.evaluate(()=>{
    window.slideFrames=[]
    const sample=()=>{
     const source=document.querySelector('[data-route-source]')
     const surface=document.querySelector('[data-route-surface]')
     window.slideFrames.push({t:performance.now(), phase:source?.dataset.routePhase, source:source?.dataset.routeSource, x:surface.getBoundingClientRect().x, visible:getComputedStyle(surface).visibility, ready:!!document.querySelector('[data-market-ready="true"]'), sourceNodes:source?.childElementCount, background:source && getComputedStyle(source).backgroundColor})
     requestAnimationFrame(sample)
    };sample()
   })
   const screenshot = async name => {
    const session = await page.context().newCDPSession(page)
    const shot = await session.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})
    fs.writeFileSync(`${process.env.TEMP}/home-correction-${width}-${name}.png`,Buffer.from(shot.data,'base64'))
    await session.detach()
   }
   const verifySlide=async (start,direction,destination)=>{
    const frames=await page.evaluate(start=>window.slideFrames.slice(start),start)
    const moving=frames.filter(f=>f.phase==='enter' && Math.abs(f.x)>1 && Math.abs(f.x)<width)
    assert(moving.length>=3,'Actual destination moves')
    assert(moving.every(f=>Math.sign(f.x)===direction),'Correct entry direction')
    assert(moving.every((f,i)=>!i || Math.abs(f.x)<=Math.abs(moving[i-1].x)+1))
    if(destination==='/listings')assert(moving.every(f=>f.ready),'Market ready before entry')
    assert(frames.filter(f=>f.phase && f.phase!=='handoff').every(f=>f.sourceNodes===1 && f.background==='rgba(0, 0, 0, 0)'), 'Source snapshot, no black cover')
    assert.equal(await page.locator('[data-route-phase]').count(),0)
    assert.equal(await page.locator('[data-route-surface]').getAttribute('style'),null)
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth))
   }
   let start=await page.evaluate(()=>window.slideFrames.length)
   if(width>=1024)await page.getByRole('navigation',{name:'Market navigation'}).getByRole('link',{name:'Home',exact:true}).click({noWaitAfter:true})
   else await page.getByRole('tab',{name:'Home',exact:true}).click({noWaitAfter:true})
   await page.locator('[data-route-phase]').waitFor()
   await page.locator('[data-route-phase]').waitFor({state:'detached',timeout:40000})
   await verifySlide(start,1,'/home')
   const root=page.locator('[data-slot="home-sidebar-demo"]')
   if(width>=1024){
    const workspace=await root.locator('[data-slot="sidebar"]').boundingBox()
    assert.equal(workspace.x,48);assert.equal(workspace.y,48)
    assert.equal(workspace.width,width-96);assert.equal(workspace.height,804)
    await root.locator('canvas[data-rendered="true"]').waitFor()
    const ambient=await root.locator('[data-home-ambient]').boundingBox()
    assert(ambient.width>width && ambient.height>900)
    const rail=root.locator('[data-slot="sidebar-body"]')
    await rail.hover();await page.waitForTimeout(350)
    assert(await rail.getByText('Back to Market',{exact:true}).isVisible())
    const surface=await root.locator('main').last().evaluate(e=>getComputedStyle(e).backgroundColor)
    assert.notEqual(surface,await rail.evaluate(e=>getComputedStyle(e).backgroundColor))
    assert.notEqual(await rail.evaluate(e=>getComputedStyle(e).borderRightColor),'rgba(0, 0, 0, 0)')
    await page.waitForTimeout(400)
    await screenshot('home')
   }else{
    await root.locator('canvas[data-rendered="true"]').waitFor()
    assert(await root.locator('[data-home-mobile-header]').isVisible())
    assert(await root.getByText('Campus Marketplace',{exact:true}).isVisible())
    assert(!(await root.locator('[data-slot="sidebar"]').isVisible()))
    const menu=root.locator('[data-smooth-dropdown]')
    await menu.getByRole('button',{name:'Show more'}).click()
    await page.waitForTimeout(350)
    await menu.getByRole('button',{name:'Listings',exact:true}).click()
    await page.waitForTimeout(350)
    await screenshot('dropdown')
    await menu.getByRole('button',{name:'Favorites',exact:true}).click()
    assert(await root.locator('main').first().getByRole('heading',{name:'Favorites'}).isVisible())
    await page.waitForTimeout(300)
    await menu.getByRole('button',{name:'Show more'}).click()
    await menu.getByRole('button',{name:'Messages',exact:true}).click()
    await menu.getByRole('button',{name:'Inbox',exact:true}).click()
    assert(await root.locator('main').first().getByRole('heading',{name:'Inbox'}).isVisible())
    await menu.getByRole('button',{name:'Show more'}).click()
    await menu.getByRole('button',{name:'Settings',exact:true}).click()
    assert(await root.locator('main').first().getByRole('heading',{name:'Settings'}).isVisible())
    await page.waitForTimeout(400)
    await screenshot('home')
   }
   start=await page.evaluate(()=>window.slideFrames.length)
   if(width>=1024)await root.getByRole('link',{name:'Back to Market',exact:true}).click({noWaitAfter:true})
   else await page.getByRole('tab',{name:'Market',exact:true}).click({noWaitAfter:true})
   await page.locator('[data-route-phase="waiting"]').waitFor()
   await screenshot('source-waiting')
   await page.locator('[data-route-phase]').waitFor({state:'detached',timeout:40000})
   await verifySlide(start,-1,'/listings')
   await page.evaluate(()=>history.back())
   await page.waitForFunction(()=>location.pathname==='/home')
   await page.locator('[data-slot="home-sidebar-demo"]').waitFor()
   assert.equal(await page.locator('[data-route-phase]').count(),0,'History remains direct')
   await page.evaluate(()=>history.forward())
   await page.waitForFunction(()=>location.pathname==='/listings')
   await page.locator('[data-market-ready="true"]').waitFor()
   await page.emulateMedia({reducedMotion:'reduce'})
   if(width>=1024)await page.getByRole('navigation',{name:'Market navigation'}).getByRole('link',{name:'Home',exact:true}).click({noWaitAfter:true})
   else await page.getByRole('tab',{name:'Home',exact:true}).click({noWaitAfter:true})
   await page.waitForFunction(()=>location.pathname==='/home')
   await page.waitForTimeout(600)
   assert.equal(await page.locator('[data-route-phase]').count(),0,'Reduced transition completes')
   if(width>=1024)await page.getByRole('link',{name:'Back to Market',exact:true}).click({noWaitAfter:true})
   else await page.getByRole('tab',{name:'Market',exact:true}).click({noWaitAfter:true})
   await page.locator('[data-market-ready="true"]').waitFor()
   await page.waitForTimeout(500)
   assert.equal(await page.locator('[data-route-phase]').count(),0)
   // Failure before route change leaves the source visible and unlocks controls.
   await page.evaluate(()=>{ window.next.router.push=()=>Promise.reject(new Error('test failure')) })
   if(width>=1024)await page.getByRole('navigation',{name:'Market navigation'}).getByRole('link',{name:'Home',exact:true}).click({noWaitAfter:true})
   else await page.getByRole('tab',{name:'Home',exact:true}).click({noWaitAfter:true})
   await page.waitForTimeout(300)
   assert.equal(await page.locator('[data-route-phase]').count(),0)
   assert.equal(await page.locator('[data-route-surface]').getAttribute('inert'),null)
   assert.deepEqual(errors,[])
   console.log(`PASS ${width}: Home surfaces/header/IA, both ready-first slide directions, source retained, no black cover, failure cleanup`)
   await page.close()
  }
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1})
