/* global document, window, getComputedStyle */
const assert = require('node:assert/strict')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright-core')
;(async () => {
  const browser = await chromium.launch({ executablePath: process.env.BROWSER_EXECUTABLE, headless: true, args: ['--enable-unsafe-swiftshader'] })
  try {
    const page = await browser.newPage({viewport:{width:390,height:900}, hasTouch:true, serviceWorkers: process.env.PRODUCTION_PREVIEW ? 'allow' : 'block'})
    const errors=[]
    page.on('pageerror',error=>errors.push(error.message))
    await page.route('**/api/auth/session',route=>route.fulfill({json:{seller:null}}))
    await page.goto(process.env.BASE_URL || 'http://localhost:3100/listings',{waitUntil:'domcontentloaded',timeout:120000})
    for(const [width, columns] of [[390,2],[768,3],[834,3],[1280,4],[1536,5]]) {
      await page.setViewportSize({width,height:900})
      await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}))
      await page.waitForTimeout(1100)
      const discover=page.locator('[data-discover]')
      const sort=page.getByRole('button',{name:'Sort',exact:true})
      const filter=page.getByRole('button',{name:'Filter',exact:true})
      const initial=await discover.boundingBox(), sortBox=await sort.boundingBox(), filterBox=await filter.boundingBox()
      const search=await page.getByRole('button',{name:'Open search'}).locator('..').boundingBox()
      assert(sortBox.x < filterBox.x)
      assert.equal(sortBox.height,search.height)
      assert.equal(filterBox.height,search.height)
      if(width<1024) assert.equal(Math.round(filterBox.x+filterBox.width),width-20)
      for(const button of [sort,filter]) assert.deepEqual(await button.evaluate(el=>({bg:getComputedStyle(el).backgroundColor,color:getComputedStyle(el).color})),{bg:'rgb(255, 255, 255)',color:'rgb(24, 24, 27)'})
      if(width<1024) assert.equal(Math.round(initial.x),20)
      if(width>=1024) assert(initial.width<=381,'Desktop Discover stays compact at rest')
      await page.getByRole('button',{name:'Favorites',exact:true}).click()
      assert.equal(await page.getByRole('button',{name:'Favorites',exact:true}).evaluate(el=>getComputedStyle(el).color),'rgb(207, 69, 69)')
      await page.getByRole('button',{name:'Open search'}).click()
      await page.waitForTimeout(1200)
      const expanded=await discover.boundingBox()
      assert(Math.abs(expanded.x+expanded.width-sortBox.x+(width<1024?10:20))<1,'Expanded search reaches right group')
      await page.getByRole('combobox',{name:'Search listings'}).fill('Local preview')
      assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth))
      await page.getByRole('button',{name:'Close search'}).click()
      await page.waitForTimeout(1100)
      for(const [button,name] of [[sort,'Sort'],[filter,'Filter']]) {
        await button.click()
        await page.waitForTimeout(1000)
        const panel=page.getByRole('region',{name:`${name} options`}), box=await panel.boundingBox(), trigger=await button.boundingBox()
        assert(Math.abs(box.x+box.width-trigger.x-trigger.width)<1)
        assert(Math.abs(box.y-trigger.y-trigger.height-8)<1)
        assert(box.x>=19 && box.x+box.width<=width)
        assert.equal(await panel.evaluate(el=>getComputedStyle(el).overflow),'hidden')
        assert.equal(await panel.locator(':scope > div').evaluate(el=>getComputedStyle(el).scrollbarGutter),'stable')
        await page.screenshot({path:`${process.env.TEMP}/market-polish-${width}-${name}.png`})
        await page.keyboard.press('Escape')
        await panel.waitFor({state:'detached'})
      }
      const grid=page.locator('[data-market-grid] > div').first()
      assert.equal(await grid.evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length),columns)
      assert.equal(await page.getByRole('navigation',{name:'Main navigation'}).count(),0)
      const nav=page.getByRole('navigation',{name:'Home and Market navigation'})
      if(width<1024) {
        assert(await nav.isVisible())
        const radios=nav.getByRole('tab')
        assert.equal(await radios.first().innerText(),'Market')
        assert.equal(await radios.nth(1).innerText(),'Home')
        assert.equal(await radios.nth(1).isDisabled(),false)
        assert.equal(await radios.nth(1).evaluate(el=>getComputedStyle(el).opacity),'1')
        assert.equal(await radios.first().getAttribute('aria-selected'),'true')
        assert.equal(await radios.nth(1).getAttribute('aria-selected'),'false')
        assert.equal(await radios.nth(1).evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(16, 16, 19)')
        assert.equal(await radios.nth(1).evaluate(el=>getComputedStyle(el).color),'rgb(255, 255, 255)')
        const count=await page.locator('[data-market-card]').count()
        await page.mouse.move(150,500)
        await page.mouse.wheel(0,20000)
        await page.waitForFunction(count=>document.querySelectorAll('[data-market-card]').length>count,count)
      } else {
        assert(!(await nav.isVisible()))
        const desktopNav=page.getByRole('navigation',{name:'Market navigation'})
        assert.equal(await desktopNav.getByRole('link',{name:'Market',exact:true}).count(),0)
        assert.equal(await desktopNav.getByRole('button',{name:'Home',exact:true}).count(),0)
        assert.equal(await desktopNav.getByRole('link',{name:'Home'}).getAttribute('href'),'/home')
        assert.equal(await page.locator('[data-market-card]').count(),15)
        assert.equal(await page.locator('[data-market-grid]').getAttribute('data-browsing'),'pagination')
        await page.getByRole('button',{name:'Next',exact:true}).click()
        assert.equal(await page.locator('[data-market-card]').count(),15)
        await page.getByRole('button',{name:'Previous',exact:true}).click()
      }
      await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}))
      await page.screenshot({path:`${process.env.TEMP}/market-polish-${width}.png`})
      assert.deepEqual(errors,[])
      console.log(`PASS ${width}: control sizing/order/colors, search expansion, anchored panels, ${columns} columns, responsive navigation/browsing`)
    }
  } finally { await browser.close() }
})().catch(error=>{console.error(error);process.exitCode=1})
