/* global window, document, getComputedStyle, requestAnimationFrame, performance */
const assert=require('node:assert/strict')
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright-core')
;(async()=>{
 const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE,headless:true,args:['--enable-unsafe-swiftshader']})
 try{
  for(const width of [390,1280,1536].filter(width=>!process.env.TEST_WIDTHS||process.env.TEST_WIDTHS.split(',').includes(String(width)))){
   const page=await browser.newPage({viewport:{width,height:900},hasTouch:width<1024,serviceWorkers:process.env.PRODUCTION_PREVIEW?'allow':'block'})
   const errors=[];page.on('pageerror',e=>errors.push(e.message))
   await page.route('**/api/auth/session',r=>r.fulfill({json:{seller:null}}))
   await page.goto('http://localhost:3100/listings',{waitUntil:'domcontentloaded',timeout:120000})
   const button=name=>page.getByRole('button',{name,exact:true})
   await button('Filter').waitFor();await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(800)
   const card=page.locator('[data-market-card] [data-slot="expandable-card"]').first()
   const sourceBox=await card.boundingBox()
   await card.evaluate(e=>{window.sourceCard=e;window.cardFrames=[];const started=performance.now();const sample=()=>{const price=e.querySelector('[data-slot="collapsed-price"]');cardFrames.push({t:performance.now()-started,hidden:e.dataset.sourceHidden==='true',price:getComputedStyle(price).visibility,dialog:!!document.querySelector('[role="dialog"]')});if(performance.now()-started<2300)requestAnimationFrame(sample)};requestAnimationFrame(sample);e.click()})
   const dialog=page.getByRole('dialog');await dialog.waitFor();await page.waitForTimeout(750)
   assert.equal(await card.getAttribute('data-source-hidden'),'true')
   assert.deepEqual(await card.boundingBox(),sourceBox,'Source reserves exact grid space')
   assert.equal(await card.locator('[data-slot="collapsed-price"]').evaluate(e=>getComputedStyle(e).visibility),'hidden')
   await page.screenshot({path:`${process.env.TEMP}/market-polish-${width}-open.png`})
   await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.waitForTimeout(60)
   assert.equal(await card.getAttribute('data-source-hidden'),'true','Still hidden during return')
   await page.screenshot({path:`${process.env.TEMP}/market-polish-${width}-return.png`})
   await dialog.waitFor({state:'detached'})
   await page.waitForFunction(()=>!window.sourceCard.dataset.sourceHidden,{timeout:4000})
   await page.waitForTimeout(100)
   assert.equal(await card.locator('[data-slot="collapsed-price"]').evaluate(e=>getComputedStyle(e).visibility),'visible')
   assert.deepEqual(await card.boundingBox(),sourceBox)
   assert(await page.evaluate(()=>cardFrames.filter(f=>f.dialog).every(f=>f.hidden && f.price==='hidden')),'No source/expanded duplicate frames')
   await page.screenshot({path:`${process.env.TEMP}/market-polish-${width}-closed.png`})
   await card.click();await page.waitForTimeout(30);await page.keyboard.press('Escape')
   await page.waitForFunction(()=>!window.sourceCard.dataset.sourceHidden,{timeout:4000})
   await page.emulateMedia({reducedMotion:'reduce'});await card.click();await dialog.waitFor();await page.keyboard.press('Escape');await dialog.waitFor({state:'detached'})
   await page.waitForFunction(()=>!window.sourceCard.dataset.sourceHidden,{timeout:4000})
   await page.emulateMedia({reducedMotion:'no-preference'})
   // All dismissal paths animate the entire surface, while the 200ms backdrop remains.
   for(const mode of ['Confirm','Cancel','backdrop','Escape','Sort']){
    const label=mode==='Sort'?'Sort':'Filter'
    await button(label).click();await page.waitForTimeout(300)
    const panel=page.getByRole('region',{name:`${label} options`,exact:true})
    if(mode==='backdrop')await page.locator('[data-market-focus-backdrop]').click({position:{x:2,y:400}})
    else if(mode==='Escape')await page.keyboard.press('Escape')
    else if(mode==='Sort')await button('Price: Low to High').click()
    else await button(mode).click()
    if(mode==='Sort')await page.waitForTimeout(150)
    await page.waitForTimeout(70)
    const state=await panel.evaluate(e=>({opacity:Number(getComputedStyle(e).opacity),transform:getComputedStyle(e).transform}))
    assert(state.opacity>0 && state.opacity<1)
    assert.equal(new DOMMatrixFallback(state.transform).y,0,'Whole panel fades without translation')
    assert.equal(await page.locator('[data-market-focus-backdrop]').count(),1)
    await page.locator('[data-market-focus-backdrop]').waitFor({state:'detached'})
   }
   if(width>=1024){
    const profile=page.getByRole('link',{name:'My Account'})
    assert.equal((await profile.boundingBox()).width,60)
    assert.equal(await profile.evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)')
    await profile.hover();await page.waitForTimeout(350)
    assert.equal(await profile.locator(':scope > span').first().evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(22, 101, 52)')
    assert.equal(await profile.locator('svg').evaluate(e=>getComputedStyle(e).color),'rgb(255, 255, 255)')
    await page.mouse.move(0,0);await page.waitForTimeout(350)
    assert.equal(await profile.locator('svg').evaluate(e=>getComputedStyle(e).color),'rgb(24, 24, 27)')
    assert.equal(await button('Return to top').count(),0)
    await button('Page 2').scrollIntoViewIfNeeded();await page.waitForTimeout(100)
    await button('Return to top').waitFor()
    assert.equal((await button('Return to top').boundingBox()).width,50)
    const capture=async(action)=>{
     await page.evaluate(action=>{window.scrollSamples=[];window.scrollCalls=[];const original=window.scrollTo.bind(window);window.previousScroll=original;window.scrollTo=options=>{scrollCalls.push({t:performance.now()-window.scrollStarted,from:scrollY,to:options.top});original(options)};window.scrollStarted=performance.now();const sample=()=>{scrollSamples.push({t:performance.now()-scrollStarted,y:scrollY,header:document.querySelector('main>header').getBoundingClientRect().y});if(performance.now()-scrollStarted<1000)requestAnimationFrame(sample)};sample();document.querySelector(action).click()},action)
     await page.waitForTimeout(1100)
     const result=await page.evaluate(()=>{window.scrollTo=previousScroll;return {calls:scrollCalls,samples:scrollSamples}})
     assert(result.samples.every(s=>s.header===0))
     assert(Math.abs(result.calls[0].to-result.samples[0].y)<2)
     assert.equal(result.calls[0].from,result.samples[0].y)
     return result
    }
    const up=await capture('[aria-label="Return to top"]')
    assert(up.calls[0].t<100,'Return starts immediately')
    assert.equal(await button('Return to top').count(),0)
    await button('Page 2').scrollIntoViewIfNeeded()
    const pagination=await capture('[aria-label="Page 2"]')
    assert(pagination.calls[0].t>=190,'Pagination retains 200ms delay')
    assert(pagination.samples.filter(s=>s.t<190).every(s=>s.y===pagination.samples[0].y))
    await button('Page 1').scrollIntoViewIfNeeded()
    await page.evaluate(()=>document.querySelector('[aria-label="Page 1"]').click());await page.waitForTimeout(280)
    await button('Return to top').click();await page.waitForTimeout(800)
    assert.equal(await button('Return to top').count(),0)
    await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>window.scrollTo({top:700,behavior:'instant'}));await button('Return to top').waitFor();await button('Return to top').click();await page.waitForTimeout(50);assert.equal(await page.evaluate(()=>scrollY),0)
   }else assert.equal(await button('Return to top').count(),0)
   assert.deepEqual(errors,[])
   console.log(`PASS ${width}: reserved/hidden source through lifecycle, completed return restore, unified panel exits${width>=1024?', Work colors, shared immediate/delayed scrolling and cancellation':''}`)
   await page.close()
  }
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1})
function DOMMatrixFallback(value){this.y=value==='none'?0:Number(value.slice(value.indexOf('(')+1,-1).split(',')[5])}
