/* global document, window, getComputedStyle */
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright-core')
const assert = require('node:assert/strict')
const base = process.env.BASE_URL || 'http://localhost:3100'
;(async () => {
  const browser = await chromium.launch({ executablePath: process.env.BROWSER_EXECUTABLE, headless: true, args: ['--enable-unsafe-swiftshader'] })
  try {
    for (const [width, columns] of (process.env.DESKTOP_ONLY ? [[1280, 4], [1536, 5]] : [[390, 2], [768, 3], [834, 3], [1280, 4], [1536, 5]]).filter(([width]) => !process.env.TEST_WIDTHS || process.env.TEST_WIDTHS.split(',').includes(String(width)))) {
      const page = await browser.newPage({ viewport: { width, height: 900 }, serviceWorkers: process.env.PRODUCTION_PREVIEW ? 'allow' : 'block', hasTouch: width < 1024 })
      const errors = []
      page.on('pageerror', (error) => errors.push(error.message))
      await page.route('**/api/auth/session', (route) => route.fulfill({ json: { seller: null } }))
      await page.goto(`${base}/listings`, { waitUntil: 'domcontentloaded', timeout: 120000 })
      const grid = page.locator('[data-market-grid] > div').first()
      await grid.waitFor()
      await page.waitForTimeout(1000)
      assert.equal(await grid.evaluate((element) => getComputedStyle(element).gridTemplateColumns.split(' ').length), columns)
      const cards = page.locator('[data-market-card]')
      assert.equal(await cards.count(), width < 1024 ? 30 : 15)
      const card = cards.first().locator('[data-slot="expandable-card"]')
      assert.equal(await card.locator(':scope > *').count(), 2)
      assert.equal(await card.innerText(), 'CA$520')
      if (width < 1024) assert(await page.getByText('Free', { exact: true }).count() > 0)
      assert.equal(await page.locator('[data-market-background]').getAttribute('data-market-background'), 'lowered')
      const nav = page.getByRole('navigation', { name: 'Home and Market navigation' })
      if (width < 1024) {
        await nav.waitFor({ state: 'visible' })
        assert.equal(await nav.getByRole('radio', { name: 'Market' }).getAttribute('aria-checked'), 'true')
        assert.equal(await nav.evaluate((element) => getComputedStyle(element).position), 'fixed')
      } else {
        assert(!(await nav.isVisible()))
        assert.equal(await page.getByRole('navigation', { name: 'Main navigation' }).count(), 0)
        assert(await page.getByRole('navigation', { name: 'Market navigation' }).isVisible())
      }
      assert.equal(await page.getByText('Market preview', { exact: false }).count(), 0)
      const brand = page.getByRole('heading', { name: 'Campus Marketplace', exact: true })
      assert.equal(await brand.isVisible(),width>=1024)
      if (width >= 1024) assert.equal(Math.round((await brand.boundingBox()).x),48)
      await page.getByRole('button', { name: 'Favorites', exact: true }).click()
      assert.equal(await page.getByRole('button', { name: 'Favorites', exact: true }).getAttribute('aria-pressed'), 'true')
      await page.getByRole('button', { name: 'Open search', exact: true }).click()
      await page.waitForTimeout(900)
      await page.getByRole('combobox', { name: 'Search listings' }).fill('Preview search')
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth))
      await page.getByRole('button', { name: 'Close search', exact: true }).click()
      await page.waitForTimeout(900)
      await page.screenshot({ path: `${process.env.TEMP}/market-layout-${width}.png` })
      await page.mouse.move(150, 500)
      await page.mouse.wheel(0, 20000)
      if (width < 1024) await page.waitForFunction(() => document.querySelectorAll('[data-market-card]').length > 30)
      else {
        assert.equal(await cards.count(), 15)
        assert.equal(await page.locator('[data-market-grid]').getAttribute('data-browsing'), 'pagination')
        await page.getByRole('button', { name: 'Next', exact: true }).click()
        assert.equal(await cards.count(), 15)
        assert(await page.getByText('Free', { exact: true }).count() > 0)
        await page.getByRole('button', { name: 'Previous', exact: true }).click()
      }
      if(width<1024) assert(await page.evaluate(() => window.scrollY) > 0)
      await page.waitForTimeout(1000)
      await page.mouse.wheel(700, 0)
      await page.waitForTimeout(300)
      assert.equal(await page.evaluate(() => window.scrollX), 0)
      assert.equal(await grid.evaluate((element) => getComputedStyle(element).transform), 'none')
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth))
      await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
      if (width < 1024) {
        const touch = await page.context().newCDPSession(page)
        await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 150, y: 680 }] })
        for (const y of [580, 480, 380, 280]) {
          await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 150, y }] })
          await page.waitForTimeout(30)
        }
        await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
        await page.waitForTimeout(500)
        assert(await page.evaluate(() => window.scrollY) > 0, 'Native vertical touch swipe scrolls')
        assert.equal(await page.evaluate(() => window.scrollX), 0)
        await touch.detach()
        await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
      }
      await page.getByRole('button', { name: 'Filter', exact: true }).click()
      await page.waitForTimeout(900)
      await page.screenshot({path: `${process.env.TEMP}/market-filter-${width}.png`})
      const triggerBox = await page.getByRole('button', { name: 'Filter', exact: true }).boundingBox()
      const panel = page.getByRole('region', { name: 'Filter options' })
      const panelBox = await panel.boundingBox()
      assert(Math.abs(panelBox.x + panelBox.width - triggerBox.x - triggerBox.width) < 1)
      assert(Math.abs(panelBox.y - triggerBox.y - triggerBox.height - 8) < 1)
      assert(panelBox.x >= 19 && panelBox.x + panelBox.width <= width)
      assert.equal(await panel.evaluate((el) => getComputedStyle(el).overflow), 'hidden')
      assert.equal(await panel.locator(':scope > div').evaluate((el) => getComputedStyle(el).scrollbarGutter), 'stable')
      await page.getByRole('combobox',{name:'Category',exact:true}).click()
      await page.getByRole('option',{name:'Electronics',exact:true}).click()
      await page.getByRole('button',{name:'Confirm',exact:true}).click()
      await page.waitForTimeout(700)
      assert.equal((await cards.count()) % 6, 0)
      await page.getByRole('button', { name: 'Filter', exact: true }).click()
      await page.getByRole('radio',{name:'On campus',exact:true}).check()
      await page.getByRole('button',{name:'Confirm',exact:true}).click()
      await page.waitForTimeout(700)
      assert.equal((await cards.count()) % 2, 0)
      await page.getByRole('button', { name: 'Sort', exact: true }).click()
      await page.waitForTimeout(900)
      const sortTrigger = await page.getByRole('button', { name: 'Sort', exact: true }).boundingBox()
      const sortPanel = await page.getByRole('region', { name: 'Sort options' }).boundingBox()
      assert(Math.abs(sortPanel.x + sortPanel.width - sortTrigger.x - sortTrigger.width) < 1)
      assert(Math.abs(sortPanel.y - sortTrigger.y - sortTrigger.height - 8) < 1)
      assert(sortPanel.x >= 19 && sortPanel.width <= 224)
      const toolbar = page.locator('[data-discover]').locator('..')
      assert.equal(await toolbar.evaluate((el) => getComputedStyle(el).flexWrap), 'nowrap')
      assert.equal(await page.getByRole('button', {name:'Filter',exact:true}).locator('span').evaluate((el)=>getComputedStyle(el).display === 'none'), width < 1024)
      await page.getByRole('button', { name: 'Price: Low to High', exact: true }).click()
      await page.waitForTimeout(700)
      assert.equal(await cards.first().locator('[data-slot="collapsed-price"]').innerText(), 'CA$60')
      await cards.first().locator('[data-slot="expandable-card"]').click()
      const dialog = page.getByRole('dialog', { name: 'Wireless headphones' })
      await dialog.waitFor({ state: 'visible' })
      await page.waitForTimeout(500)
      assert(await dialog.getByRole('button', { name: 'Close', exact: true }).isVisible())
      assert(await dialog.getByRole('button', { name: 'Contact seller', exact: true }).isVisible())
      await page.keyboard.press('Escape')
      await dialog.waitFor({ state: 'detached' })
      if (width < 1024) {
        assert(await nav.getByRole('radio', { name: 'Home' }).isDisabled())
        assert.equal(page.url(), base + '/listings')
      }
      if (width === 390) {
        await page.setViewportSize({width, height:420})
        await page.getByRole('button', {name:'Filter',exact:true}).click()
        await page.waitForTimeout(900)
        const scroll = page.getByRole('region', {name:'Filter options'}).locator(':scope > div')
        assert(await scroll.evaluate((el)=>el.scrollHeight > el.clientHeight))
        assert(await scroll.evaluate((el)=>{el.scrollTop=50;return el.scrollTop > 0}))
        const shell = await page.getByRole('region', {name:'Filter options'}).boundingBox()
        const inner = await scroll.boundingBox()
        assert(inner.y >= shell.y + 12 && inner.y + inner.height <= shell.y + shell.height - 12)
      }
      assert.deepEqual(errors, [])
      console.log(`PASS ${width}: ${columns} columns, responsive browsing, no X drift, filter/location/sort, reused overlay, responsive navigation`)
      await page.close()
    }
  } finally { await browser.close() }
})().catch((error) => { console.error(error); process.exitCode = 1 })
