/* global window, document, getComputedStyle */
const assert = require('node:assert/strict')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright-core')
;(async () => {
  const browser = await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE,headless:true,args:['--enable-unsafe-swiftshader']})
  try {
    const page=await browser.newPage({viewport:{width:390,height:900},hasTouch:true,serviceWorkers:process.env.PRODUCTION_PREVIEW?'allow':'block'})
    const errors=[];page.on('pageerror',e=>errors.push(e.message))
    await page.route('**/api/auth/session',r=>r.fulfill({json:{seller:null}}))
    await page.goto('http://localhost:3100/listings',{waitUntil:'domcontentloaded',timeout:120000})
    const nav=page.getByRole('navigation',{name:'Home and Market navigation'})
    const market=nav.getByRole('tab',{name:'Market',exact:true})
    const home=nav.getByRole('tab',{name:'Home',exact:true})
    const indicator=nav.locator('[role="tab"][aria-selected="true"] > span[aria-hidden]')
    await market.waitFor();await page.waitForTimeout(800)
    assert.equal(await nav.count(),1);assert.equal(await nav.getByRole('radio').count(),0)
    assert.equal(await nav.getByRole('tab').count(),2)
    assert.equal((await nav.boundingBox()).width,230);assert.equal((await nav.boundingBox()).height,56)
    assert.equal((await market.boundingBox()).width,(await home.boundingBox()).width)
    assert((await market.boundingBox()).x<(await home.boundingBox()).x)
    assert.equal(await indicator.count(),1)
    assert.equal(await indicator.evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)')
    assert.equal(await market.evaluate(e=>getComputedStyle(e).color),'rgb(24, 24, 27)')
    assert.equal(await home.evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(16, 16, 19)')
    assert.equal(await nav.evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(16, 16, 19)')
    const box=await indicator.boundingBox();await page.waitForTimeout(1100)
    assert.deepEqual(await indicator.boundingBox(),box,'Idle indicator is still')
    await page.screenshot({path:`${process.env.TEMP}/market-fluid-idle.png`})
    await home.tap();await page.waitForURL('**/home')
    await page.locator('[data-slot="home-sidebar-demo"]').waitFor()
    await page.waitForTimeout(700)
    assert.equal(await home.getAttribute('aria-selected'),'true')
    assert.equal((await indicator.boundingBox()).x,(await home.boundingBox()).x)
    assert.equal(new URL(page.url()).pathname,'/home','Home is real routing')
    await page.screenshot({path:`${process.env.TEMP}/market-fluid-home.png`})
    await market.tap();await page.waitForURL('**/listings');await page.waitForTimeout(700)
    assert.deepEqual(await indicator.boundingBox(),box)
    await home.hover();await page.waitForTimeout(500)
    assert.equal(await market.getAttribute('aria-selected'),'true','Hover does not move selection')
    assert.deepEqual(await indicator.boundingBox(),box)
    await market.focus();await page.keyboard.press('ArrowRight')
    assert(await home.evaluate(e=>e===document.activeElement));assert.equal(await market.getAttribute('aria-selected'),'true')
    assert.equal(await home.evaluate(e=>getComputedStyle(e).outlineStyle),'solid','Visible keyboard focus')
    await page.keyboard.press('Enter');await page.waitForURL('**/home');assert.equal(await home.getAttribute('aria-selected'),'true')
    await home.focus()
    await page.keyboard.press('ArrowUp');assert(await market.evaluate(e=>e===document.activeElement))
    await page.keyboard.press(' ');await page.waitForURL('**/listings');assert.equal(await market.getAttribute('aria-selected'),'true')
    await market.focus()
    await page.keyboard.press('End');assert(await home.evaluate(e=>e===document.activeElement))
    await page.keyboard.press('Home');assert(await market.evaluate(e=>e===document.activeElement))
    await page.keyboard.press('ArrowLeft');assert(await home.evaluate(e=>e===document.activeElement))
    await page.keyboard.press('ArrowDown');assert(await market.evaluate(e=>e===document.activeElement))
    await page.waitForTimeout(700)
    await nav.evaluate(e=>window.fluidNav=e)
    const original=await nav.boundingBox()
    assert.equal(900-original.y-original.height,8)
    const checkLayer=async(label)=>{
      assert(await nav.evaluate(e=>e===window.fluidNav && e.isConnected),'Same mounted nav through overlay')
      assert.deepEqual(await nav.boundingBox(),original,'Physical nav position preserved')
      const backdrop=page.locator('[data-market-focus-backdrop]').or(page.locator('[role="dialog"]').locator('..').locator(':scope > div').first())
      assert(await backdrop.count()>0)
      assert.equal(await backdrop.first().evaluate(e=>getComputedStyle(e).backdropFilter),'blur(4px)')
      assert.equal(await nav.locator('..').evaluate(e=>getComputedStyle(e).zIndex),'30')
      await page.screenshot({path:`${process.env.TEMP}/market-fluid-${label}.png`})
    }
    const button=name=>page.getByRole('button',{name,exact:true})
    for(const label of ['Filter','Sort']){
      await button(label).click();await page.waitForTimeout(350);await checkLayer(label.toLowerCase())
      await page.keyboard.press('Escape');await page.locator('[data-market-focus-backdrop]').waitFor({state:'detached'})
    }
    await button('Open search').click();await page.waitForTimeout(700)
    await page.getByRole('combobox',{name:'Search listings'}).fill('mon');await page.waitForTimeout(350);await checkLayer('search')
    await page.keyboard.press('Escape');await page.locator('[data-market-focus-backdrop]').waitFor({state:'detached'})
    await page.locator('[data-market-card] [data-slot="expandable-card"]').first().click();await page.getByRole('dialog').waitFor();await page.waitForTimeout(700);await checkLayer('card')
    await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'detached'})
    for(const width of [390,768,834,1280,1536]){
      await page.setViewportSize({width,height:900});await page.waitForTimeout(250)
      assert.equal(await nav.isVisible(),width<1024)
      if(width<1024){const r=await nav.boundingBox();assert.equal(r.width,230);assert.equal(r.height,56);assert.equal(900-r.y-r.height,8);assert(Math.abs(r.x+r.width/2-width/2)<1)}
      else assert.equal(await page.getByRole('link',{name:'Home'}).evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)')
      assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth))
      console.log(`PASS ${width}: responsive Fluid Tabs visibility/position, no overflow, desktop unchanged`)
    }
    assert.deepEqual(errors,[])
    console.log('PASS 390: pathname selection, real Home/Market routing, keyboard keys/focus, no hover/idle motion, persistent layering behind Search/Filter/Sort/card')
  } finally {await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1})
