/* global window, document, getComputedStyle, requestAnimationFrame */
const assert = require('node:assert/strict')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright-core')
;(async () => {
  const browser = await chromium.launch({ executablePath: process.env.BROWSER_EXECUTABLE, headless: true, args: ['--enable-unsafe-swiftshader'] })
  try {
    const page = await browser.newPage({viewport:{width:390,height:900},hasTouch:true,serviceWorkers: process.env.PRODUCTION_PREVIEW ? 'allow' : 'block'})
    const errors=[]
    page.on('pageerror', e=>errors.push(e.message))
    await page.route('**/api/auth/session', r=>r.fulfill({json:{seller:null}}))
    await page.goto('http://localhost:3100/listings',{waitUntil:'domcontentloaded',timeout:120000})
    await page.getByRole('tab',{name:'Market',exact:true}).waitFor()
    const input=page.getByRole('combobox',{name:'Search listings'})
    const button=name=>page.getByRole('button',{name,exact:true})
    const panel=page.getByRole('listbox',{name:'Search suggestions'})
    const backdrop=page.locator('[data-market-focus-backdrop]')
    const cards=page.locator('[data-market-card]')
    const matchesOnly=async title=>{
      const names=await cards.locator('[data-slot="expandable-card"]').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('aria-label')))
      assert(names.length>0)
      assert(names.every(name=>name.startsWith(`Open example listing: ${title},`)))
      if(page.viewportSize().width>=1024)assert.equal(names.length,1)
    }
    const done=async()=>{await backdrop.waitFor({state:'detached'});await page.waitForTimeout(100)}
    const edit=async query=>{
      await page.evaluate(()=>{window.searchBlurFrames=[];const started=Date.now();const sample=()=>{const el=document.querySelector('[data-market-focus-backdrop]');if(el)window.searchBlurFrames.push(Number(getComputedStyle(el).opacity));if(Date.now()-started<1500)requestAnimationFrame(sample)};requestAnimationFrame(sample)})
      await button('Open search').click();await page.waitForTimeout(700)
      if(query==='mon' && !(await input.inputValue()))await input.type(query,{delay:60})
      else await input.fill(query)
      await panel.waitFor();await page.waitForTimeout(300)
      assert(await page.evaluate(()=>window.searchBlurFrames.some(n=>n>0&&n<1)),'Blur enters progressively')
      assert.equal(await input.inputValue(),query)
    }
    for(const [width,columns] of [[390,2],[768,3],[834,3],[1280,4],[1536,5]].filter(([width])=>!process.env.TEST_WIDTHS||process.env.TEST_WIDTHS.split(',').includes(String(width)))) {
      await page.setViewportSize({width,height:900});await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(1000)
      const url=page.url(), originalCount=await cards.count()
      await button('Favorites').click()
      assert.equal(await button('Favorites').getAttribute('aria-pressed'),'true')
      await edit('mon')
      assert.equal(await cards.count(),originalCount,'Typing must not apply')
      assert((await panel.getByRole('option').count())<=5)
      assert(await panel.getByRole('option',{name:'24-inch monitor',exact:true}).isVisible())
      const sr=await page.locator('[data-discover]').boundingBox(), pr=await panel.boundingBox(), sort=await button('Sort').boundingBox()
      assert(Math.abs(sr.width-pr.width)<1);assert(Math.abs(pr.y-sr.y-sr.height-8)<1)
      await page.screenshot({path:`${process.env.TEMP}/market-search-${width}.png`})
      assert(sr.x+sr.width<sort.x, JSON.stringify({sr,sort}));assert(pr.x>=19&&pr.x+pr.width<=width)
      assert.equal(await page.locator('[data-discover]').evaluate(e=>getComputedStyle(e).filter),'none')
      assert.equal(await panel.evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(32, 26, 41)')
      assert.equal(await page.locator('main > header').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(11, 11, 11)')
      await page.screenshot({path:`${process.env.TEMP}/market-search-${width}.png`})
      await input.press('Enter');assert.equal(await backdrop.count(),1)
      await page.waitForTimeout(70)
      const alpha=Number(await backdrop.evaluate(e=>getComputedStyle(e).opacity));assert(alpha>0&&alpha<1)
      assert(await panel.isVisible(),'Suggestions retained through exit')
      await done();await matchesOnly('24-inch monitor');assert.equal(await input.inputValue(),'mon')
      assert.equal(page.url(),url)
      await input.click();await input.fill('');await done();await matchesOnly('24-inch monitor')
      await input.press('Escape');await page.waitForTimeout(100);assert.equal(await input.inputValue(),'mon')
      await input.click();await input.fill('moni');await page.waitForTimeout(300)
      await backdrop.click({position:{x:width-3,y:400}});await done()
      assert.equal(await input.inputValue(),'mon');await matchesOnly('24-inch monitor')
      await input.click();await input.fill('head');await input.press('Escape');await done()
      assert.equal(await input.inputValue(),'mon');await matchesOnly('24-inch monitor')
      await button('Sort').click();await page.waitForTimeout(300)
      await button('Price: Low to High').click();await done();await matchesOnly('24-inch monitor')
      await button('Filter').click();await page.waitForTimeout(300)
      await page.getByRole('radio',{name:'On campus',exact:true}).check();await button('Confirm').click();await done()
      assert.equal(await cards.count(),0,'Search AND place filter')
      await button('Close search').click();await page.waitForTimeout(700)
      assert.equal(await button('Favorites').getAttribute('aria-pressed'),'true')
      assert((await cards.count())>=10 && (await cards.count())%10===0,'Clear preserves place filter and infinite batches')
      await button('Filter').click();await page.waitForTimeout(300)
      assert(await page.getByRole('radio',{name:'On campus',exact:true}).isChecked())
      await page.getByRole('radio',{name:'All places',exact:true}).check();await button('Confirm').click();await done()
      await edit('  MONITOR   ');await panel.getByRole('option',{name:'Search for "monitor"',exact:true}).click();await done()
      assert.equal(await input.inputValue(),'monitor')
      await matchesOnly('24-inch monitor')
      await input.click();await input.fill('mon');await page.waitForTimeout(300)
      await panel.getByRole('option',{name:'24-inch monitor',exact:true}).click()
      await done()
      assert.equal(await page.getByRole('dialog').count(),0,'Listing suggestion filters grid instead of opening a card')
      assert.equal(await input.inputValue(),'24-inch monitor');await matchesOnly('24-inch monitor')
      await cards.locator('[data-slot="expandable-card"]').first().click()
      const dialog=page.getByRole('dialog',{name:'24-inch monitor',exact:true})
      await dialog.waitFor();await page.waitForTimeout(650)
      assert(await dialog.isVisible());assert(await dialog.getByRole('button',{name:'Close',exact:true}).isVisible())
      assert.equal(Math.round((await page.locator('main > header').boundingBox()).y),0)
      await page.screenshot({path:`${process.env.TEMP}/market-search-${width}-listing.png`})
      await page.keyboard.press('Escape');await dialog.waitFor({state:'detached'});await page.waitForTimeout(100)
      assert.equal(await input.inputValue(),'24-inch monitor');await matchesOnly('24-inch monitor')
      await input.click();await input.fill('mon');await page.waitForTimeout(300)
      await panel.getByRole('option',{name:'Electronics — Monitors',exact:true}).click();await done()
      await matchesOnly('24-inch monitor')
      await button('Filter').click();await page.waitForTimeout(300)
      assert.equal(await page.getByRole('combobox',{name:'Category',exact:true}).innerText(),'Electronics')
      assert.equal(await page.getByRole('combobox',{name:'Subcategory',exact:true}).innerText(),'Monitors')
      await page.getByRole('combobox',{name:'Category',exact:true}).click();await page.waitForTimeout(200)
      await page.getByRole('option',{name:'All categories',exact:true}).click();await page.waitForTimeout(200)
      await button('Confirm').click();await done()
      await edit('zzzz-no-match');assert.equal(await panel.getByRole('option').count(),1)
      await input.press('Enter');await done();assert.equal(await cards.count(),0)
      assert.equal(await page.getByRole('status').innerText(),'No listings found for "zzzz-no-match"')
      await button('Close search').click();await page.waitForTimeout(700)
      await button('Sort').click();await page.waitForTimeout(300);await button('Newest').click();await done()
      await edit('bike');await input.press('Enter');await done()
      await button('Sort').click();await page.waitForTimeout(300);await button('Price: Low to High').click();await done()
      assert.equal(await input.inputValue(),'bike')
      assert.deepEqual(await cards.locator('[data-slot="collapsed-price"]').allTextContents().then(values=>values.slice(0,3)),['CA$12','CA$22','CA$180'])
      await button('Close search').click();await page.waitForTimeout(700)
      await edit('head');await input.press('ArrowDown');assert(await input.getAttribute('aria-activedescendant'));await input.press('Enter');await done();await matchesOnly('Wireless headphones')
      await button('Close search').click();await page.waitForTimeout(700)
      await button('Sort').click();await page.waitForTimeout(300);await button('Newest').click();await done()
      if(width>=1024){await button('Page 2').click();await page.waitForTimeout(1100);await edit('head');await input.press('Enter');await done();assert.equal(await button('Page 1').getAttribute('aria-current'),'page');assert.equal(await cards.count(),1);await button('Close search').click();await page.waitForTimeout(700)}
      assert.equal(await page.locator('[data-market-grid] > div').first().evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),columns)
      assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth))
      assert.deepEqual(errors,[])
      console.log(`PASS ${width}: draft/apply/dismiss/clear, suggestions <=5, sharp search, blur exit, listing shortcut and manual card open, category/sort/place composition, ${columns} columns`)
    }
  } finally {await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1})
