/* global document, window, getComputedStyle, requestAnimationFrame */
const assert = require('node:assert/strict')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright-core')
;(async () => {
  const browser = await chromium.launch({ executablePath: process.env.BROWSER_EXECUTABLE, headless: true, args: ['--enable-unsafe-swiftshader'] })
  try {
    // Production registers the existing PWA worker; blocking it breaks that registrar.
    const page = await browser.newPage({ viewport: { width: 390, height: 900 }, hasTouch: true, serviceWorkers: process.env.PRODUCTION_PREVIEW ? 'allow' : 'block' })
    const errors = []
    page.on('pageerror', e => errors.push(e.message))
    await page.route('**/api/auth/session', r => r.fulfill({ json: { seller: null } }))
    await page.goto('http://localhost:3100/listings', { waitUntil: 'domcontentloaded', timeout: 120000 })
    const trigger = name => page.getByRole('button', { name, exact: true })
    const backdrop = page.locator('[data-market-focus-backdrop]')
    const choose = async (name, option) => {
      await page.getByRole('combobox', { name, exact: true }).click()
      const list = page.getByRole('listbox', { name, exact: true })
      await list.waitFor()
      await page.waitForTimeout(200)
      const menu = await list.locator('..').boundingBox(), field = await page.getByRole('combobox', { name, exact: true }).boundingBox()
      assert(Math.abs(menu.width - field.width) < 1)
      assert(Math.abs(menu.y - field.y - field.height - 6) < 1)
      assert(menu.x >= 19 && menu.x + menu.width <= page.viewportSize().width)
      if (name === 'Category') await page.screenshot({ path: `${process.env.TEMP}/market-glide-${page.viewportSize().width}.png` })
      assert.equal(await list.evaluate(el => getComputedStyle(el).scrollbarColor), 'rgba(0, 0, 0, 0) rgba(0, 0, 0, 0)')
      await list.getByRole('option', { name: option, exact: true }).click()
      await list.waitFor({ state: 'detached' })
    }
    const open = async name => {
      const original = await trigger(name).boundingBox()
      await page.evaluate(() => {
        window.marketBlurFrames = []
        const start = performance.now()
        const sample = () => {
          const el = document.querySelector('[data-market-focus-backdrop]')
          if (el) window.marketBlurFrames.push(Number(getComputedStyle(el).opacity))
          if (performance.now() - start < 500) requestAnimationFrame(sample)
        }
        requestAnimationFrame(sample)
      })
      await trigger(name).click()
      await page.waitForTimeout(300)
      assert(await page.evaluate(() => window.marketBlurFrames.some(n => n > 0 && n < 1)), 'Blur enters progressively')
      const panel = page.getByRole('region', { name: name + ' options', exact: true })
      const r = await panel.boundingBox()
      assert(Math.abs(r.x + r.width - original.x - original.width) < 1)
      assert(Math.abs(r.y - original.y - original.height - 8) < 1)
      assert(r.x >= 19)
      assert.equal(await backdrop.count(), 1)
      assert.equal(await panel.evaluate(el => getComputedStyle(el).filter), 'none')
      assert.equal(await trigger(name).evaluate(el => getComputedStyle(el).filter), 'none')
      assert.equal(await panel.getByRole('region').evaluate(el => getComputedStyle(el).scrollbarColor), 'rgba(0, 0, 0, 0) rgba(0, 0, 0, 0)')
      assert.equal(await panel.evaluate(el => getComputedStyle(el).borderTopWidth), '1px')
      return panel
    }
    const dismissed = async () => { await backdrop.waitFor({ state: 'detached' }); await page.waitForTimeout(50) }
    for (const [width, columns] of [[390, 2], [768, 3], [834, 3], [1280, 4], [1536, 5]].filter(([width]) => !process.env.TEST_WIDTHS || process.env.TEST_WIDTHS.split(',').includes(String(width)))) {
      await page.setViewportSize({ width, height: 900 })
      await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
      await page.waitForTimeout(1000)
      const header = page.locator('main > header')
      assert.equal(await header.count(), 1)
      assert.equal(await header.evaluate(el => getComputedStyle(el).position), 'sticky')
      assert.equal(await header.evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(11, 11, 11)')
      assert.equal(await header.evaluate(el => getComputedStyle(el).backdropFilter), 'none')
      if (width < 1024) {
        const mobileBrand = header.locator('span').filter({ hasText: /^Campus Marketplace$/ })
        assert(await mobileBrand.isVisible())
        assert.equal(await mobileBrand.evaluate(el => getComputedStyle(el).color), 'rgb(255, 255, 255)')
        assert.equal(await mobileBrand.evaluate(el => getComputedStyle(el).fontWeight), '700')
        assert.equal(Math.round((await header.boundingBox()).height), 98)
      }
      const brand = page.getByRole('heading', { name: 'Campus Marketplace', exact: true })
      assert.equal(await brand.isVisible(), width >= 1024)
      const grid = page.locator('[data-market-grid] > div').first()
      assert.equal(await grid.evaluate(el => getComputedStyle(el).gridTemplateColumns.split(' ').length), columns)
      const hb = await header.boundingBox(), gb = await grid.boundingBox()
      assert.equal(Math.round(gb.y - hb.y - hb.height), width < 1024 ? 22 : 28)
      const search = await trigger('Open search').locator('..').boundingBox()
      const sb = await trigger('Sort').boundingBox(), fb = await trigger('Filter').boundingBox()
      assert.equal(sb.height, search.height); assert.equal(fb.height, search.height)
      assert(sb.x < fb.x)
      assert.equal(Math.round(search.x), width < 1024 ? 20 : Math.round((await brand.boundingBox()).x + (await brand.boundingBox()).width + 20))
      if (width >= 1024) {
        const profile = page.getByRole('link', { name: 'My Account' })
        const pb = await profile.boundingBox(), bb = await brand.boundingBox()
        for (const b of [search, sb, fb, pb]) assert(Math.abs(b.y + b.height / 2 - bb.y - bb.height / 2) < 1)
        assert.equal(await profile.getAttribute('href'), '/profile/listings')
        assert.equal(pb.height, search.height); assert.equal(pb.width, pb.height)
        assert.equal(await profile.evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(255, 255, 255)')
        const sweep = profile.locator(':scope > span').first(), idle = await sweep.evaluate(el => getComputedStyle(el).transform)
        await profile.hover(); await page.waitForTimeout(350)
        assert.notEqual(await sweep.evaluate(el => getComputedStyle(el).transform), idle)
        assert.equal(await sweep.evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(59, 7, 100)')
        assert.equal(await profile.locator('svg').evaluate(el => getComputedStyle(el).color), 'rgb(255, 255, 255)')
        await page.mouse.move(0, 0); await page.waitForTimeout(350)
        assert.equal(await sweep.evaluate(el => getComputedStyle(el).transform), idle)
      } else {
        const nav = page.getByRole('navigation', { name: 'Home and Market navigation' })
        assert.equal((await nav.boundingBox()).height, 72)
        assert.equal(await nav.getByRole('radio').first().innerText(), 'Market')
        assert.equal(await nav.getByRole('radio').nth(1).innerText(), 'Home')
        assert.equal(await nav.getByRole('radio').nth(1).evaluate(el => getComputedStyle(el).opacity), '1')
        assert.equal(await nav.getByRole('radio').first().locator(':scope > span').evaluate(el => getComputedStyle(el).height), '48px')
        assert.equal(await nav.evaluate(el => getComputedStyle(el).backgroundColor), 'rgba(10, 10, 14, 0.42)')
        assert.equal(await nav.evaluate(el => getComputedStyle(el).bottom), '8px')
      }
      await trigger('Favorites').click()
      assert.equal(await trigger('Favorites').evaluate(el => getComputedStyle(el).color), 'rgb(207, 69, 69)')
      await trigger('Open search').click(); await page.waitForTimeout(1000)
      const expanded = await page.locator('[data-discover]').boundingBox()
      assert(expanded.x + expanded.width < (await trigger('Sort').boundingBox()).x)
      await trigger('Close search').click(); await page.waitForTimeout(1000)
      const sortPanel = await open('Sort')
      await sortPanel.getByRole('button', { name: 'Price: Low to High', exact: true }).click()
      await dismissed()
      const count = await page.locator('[data-market-card]').count()
      await open('Filter'); assert.equal(await page.locator('select').count(), 0)
      if (width === 390) {
        await page.getByRole('combobox', { name: 'Category', exact: true }).click()
        const list = page.getByRole('listbox', { name: 'Category', exact: true })
        await page.waitForTimeout(220)
        assert(await list.evaluate(el => el.scrollHeight > el.clientHeight))
        const lr = await list.boundingBox()
        await page.mouse.move(lr.x + 10, lr.y + 20); await page.mouse.wheel(0, 80)
        await page.waitForTimeout(100)
        assert.equal(await list.evaluate(el => getComputedStyle(el).scrollbarColor), 'rgb(245, 245, 245) rgba(0, 0, 0, 0)')
        await page.waitForTimeout(700)
        assert.equal(await list.evaluate(el => getComputedStyle(el).scrollbarColor), 'rgba(0, 0, 0, 0) rgba(0, 0, 0, 0)')
        await page.keyboard.press('Escape')
        await list.waitFor({ state: 'detached' })
        assert.equal(await backdrop.count(), 1, 'Glide Escape closes its own menu first')
      }
      await choose('Category', 'Home & Dorm'); await choose('Subcategory', 'Furniture')
      await page.getByRole('radio', { name: 'On campus', exact: true }).check()
      assert.equal(await page.locator('[data-market-card]').count(), count)
      await trigger('Cancel').click(); await dismissed()
      assert.equal(await page.locator('[data-market-card]').count(), count)
      await open('Filter'); await choose('Category', 'Home & Dorm'); await choose('Subcategory', 'Furniture')
      await page.getByRole('radio', { name: 'On campus', exact: true }).check()
      await trigger('Confirm').click(); await dismissed(); await open('Filter')
      assert.equal(await page.getByRole('combobox', { name: 'Category', exact: true }).innerText(), 'Home & Dorm')
      assert.equal(await page.getByRole('combobox', { name: 'Subcategory', exact: true }).innerText(), 'Furniture')
      assert(await page.getByRole('radio', { name: 'On campus', exact: true }).isChecked())
      await choose('Category', 'Electronics')
      assert.equal(await page.getByRole('combobox', { name: 'Subcategory', exact: true }).innerText(), 'All subcategories')
      await trigger('Cancel').click(); await dismissed()
      await open('Filter'); await choose('Category', 'All categories')
      await page.getByRole('radio', { name: 'All places', exact: true }).check()
      await trigger('Confirm').click(); await dismissed()
      await open('Filter')
      await page.screenshot({ path: `${process.env.TEMP}/market-sticky-${width}-filter.png` })
      // The exit must retain both the backdrop and crisp active trigger midway.
      await page.keyboard.press('Escape'); assert.equal(await backdrop.count(), 1)
      await page.waitForTimeout(70)
      const alpha = Number(await backdrop.evaluate(el => getComputedStyle(el).opacity))
      assert(alpha > 0 && alpha < 1)
      assert.equal(await trigger('Filter').evaluate(el => getComputedStyle(el).filter), 'none')
      await dismissed()
      assert.equal(await page.getByRole('dialog').count(), 0)
      if (width === 390) {
        await page.setViewportSize({ width, height: 320 })
        const panel = await open('Filter')
        const scroll = panel.getByRole('region')
        assert(await scroll.evaluate(el => el.scrollHeight > el.clientHeight))
        await scroll.evaluate(el => { el.scrollTop = 10 })
        await page.waitForTimeout(100)
        assert.equal(await scroll.evaluate(el => getComputedStyle(el).scrollbarColor), 'rgba(0, 0, 0, 0) rgba(0, 0, 0, 0)')
        const r = await scroll.boundingBox()
        await page.mouse.move(r.x + 8, r.y + 8); await page.mouse.wheel(0, 40)
        await page.waitForTimeout(100)
        assert.equal(await scroll.evaluate(el => getComputedStyle(el).scrollbarColor), 'rgb(245, 245, 245) rgba(0, 0, 0, 0)')
        await page.waitForTimeout(700)
        assert.equal(await scroll.evaluate(el => getComputedStyle(el).scrollbarColor), 'rgba(0, 0, 0, 0) rgba(0, 0, 0, 0)')
        await backdrop.click({ position: { x: 4, y: 4 } }); await dismissed()
        assert.equal(await page.getByRole('dialog').count(), 0)
        await page.setViewportSize({ width, height: 900 })
      }
      await page.screenshot({ path: `${process.env.TEMP}/market-sticky-${width}.png` })
      // Preserve the exact base header/nav nodes and their positions through card presence.
      await header.evaluate(el => { window.marketHeaderNode = el })
      const headerBefore = await header.boundingBox()
      await page.locator('[data-slot="expandable-card"]').first().click()
      const dialog = page.getByRole('dialog')
      await dialog.waitFor(); await page.waitForTimeout(650)
      assert(await page.evaluate(() => window.marketHeaderNode === document.querySelector('main > header')))
      assert.deepEqual(await header.boundingBox(), headerBefore)
      const cardBounds = await dialog.boundingBox()
      if (width < 1024) {
        const nav = page.getByRole('navigation', { name: 'Home and Market navigation', includeHidden: true })
        assert(await nav.isVisible())
        assert(cardBounds.y >= headerBefore.y + headerBefore.height + 11)
        assert(cardBounds.y + cardBounds.height < (await nav.boundingBox()).y)
        const cardBackdrop = page.locator('[data-slot="listing-overlay"] > div').first()
        assert.equal(await cardBackdrop.evaluate(el => getComputedStyle(el).backgroundColor), 'rgba(8, 5, 14, 0.18)')
        assert.equal(await cardBackdrop.evaluate(el => getComputedStyle(el).backdropFilter), 'blur(4px)')
      }
      await page.screenshot({ path: `${process.env.TEMP}/market-polish-${width}-expanded.png` })
      await page.keyboard.press('Escape')
      await page.waitForTimeout(70)
      const cardExitAlpha = Number(await page.locator('[data-slot="listing-overlay"] > div').first().evaluate(el => getComputedStyle(el).opacity))
      assert(cardExitAlpha > 0 && cardExitAlpha < 1, 'Card backdrop fades through exit')
      assert.deepEqual(await header.boundingBox(), headerBefore)
      await dialog.waitFor({ state: 'detached' }); await page.waitForTimeout(100)
      assert(await page.evaluate(() => window.marketHeaderNode === document.querySelector('main > header')))
      assert.deepEqual(await header.boundingBox(), headerBefore)
      if (width < 1024) {
        const before = await page.locator('[data-market-card]').count()
        await page.mouse.move(150, 500); await page.mouse.wheel(0, 20000)
        await page.waitForFunction(n => document.querySelectorAll('[data-market-card]').length > n, before)
        assert.equal(Math.round((await header.boundingBox()).y), 0)
        const scrolledHeader = await header.boundingBox()
        const scrollBeforeCard = await page.evaluate(() => window.scrollY)
        await page.evaluate(() => {
          const card = Array.from(document.querySelectorAll('[data-slot="expandable-card"]')).find(el => {
            const r = el.getBoundingClientRect()
            return r.top >= 120 && r.top < window.innerHeight - 150
          })
          if (!card) throw new Error('No visible card after infinite append')
          card.click()
        })
        await dialog.waitFor(); await page.waitForTimeout(650)
        assert.deepEqual(await header.boundingBox(), scrolledHeader, 'Scroll lock preserves sticky header position')
        await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'detached' })
        await page.waitForTimeout(100)
        assert.deepEqual(await header.boundingBox(), scrolledHeader)
        assert.equal(await page.evaluate(() => window.scrollY), scrollBeforeCard)
        assert(await page.evaluate(() => window.marketHeaderNode === document.querySelector('main > header')))
      } else {
        const pages = page.getByRole('navigation', { name: 'Listing pages' })
        await pages.scrollIntoViewIfNeeded()
        const desktopHeaderScrolled = await header.boundingBox()
        await page.evaluate(() => {
          const card = Array.from(document.querySelectorAll('[data-slot="expandable-card"]')).find(el => {
            const r = el.getBoundingClientRect()
            return r.top >= 120 && r.top < window.innerHeight - 150
          })
          if (!card) throw new Error('No visible desktop card at pagination')
          card.click()
        })
        await dialog.waitFor(); await page.waitForTimeout(650)
        assert.deepEqual(await header.boundingBox(), desktopHeaderScrolled, 'Desktop scroll lock preserves header too')
        await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'detached' }); await page.waitForTimeout(100)
        assert.deepEqual(await header.boundingBox(), desktopHeaderScrolled)
        await page.evaluate(() => {
          window.marketScrollCalls = []
          const original = window.scrollTo.bind(window)
          window.marketOriginalScrollTo = original
          window.scrollTo = (...args) => { window.marketScrollCalls.push({ args, time: Date.now() }); original(...args) }
        })
        const started = await page.evaluate(() => { document.querySelector('[aria-label="Page 2"]').click(); return Date.now() })
        assert.equal(await pages.getByRole('button', { name: 'Page 2', exact: true }).getAttribute('aria-current'), 'page')
        await page.waitForTimeout(100)
        assert.equal(await page.evaluate(() => window.marketScrollCalls.length), 0)
        await page.waitForTimeout(180)
        let calls = await page.evaluate(() => window.marketScrollCalls)
        assert(calls.length > 1); assert(calls[0].time - started >= 180 && calls[0].time - started < 400)
        assert.equal(calls[0].args[0].behavior, 'instant')
        await page.waitForTimeout(1200)
        calls = await page.evaluate(() => window.marketScrollCalls)
        const total = Math.abs(calls.at(-1).args[0].top - calls[0].args[0].top)
        assert(total > 100)
        const midpoint = calls[Math.floor(calls.length / 2)].args[0].top
        assert(Math.abs(midpoint - calls[0].args[0].top) / total < 0.3, 'Cubic ease-in starts gently')
        assert((await grid.boundingBox()).y >= (await header.boundingBox()).height)
        assert.equal(await page.locator('[data-market-card]').count(), 15)
        await pages.scrollIntoViewIfNeeded()
        await page.evaluate(() => { window.marketScrollCalls = []; document.querySelector('[aria-label="Page 1"]').click() })
        await page.waitForTimeout(70)
        await page.evaluate(() => document.querySelector('[aria-label="Page 2"]').click())
        await page.waitForTimeout(300)
        assert((await page.evaluate(() => window.marketScrollCalls.length)) > 1)
        await page.waitForTimeout(1000)
        // Replace an active animation, not just a pending timer.
        await pages.scrollIntoViewIfNeeded()
        await page.evaluate(() => document.querySelector('[aria-label="Page 1"]').click())
        await page.waitForTimeout(300)
        const replacement = await page.evaluate(() => { window.marketScrollCalls = []; document.querySelector('[aria-label="Page 2"]').click(); return Date.now() })
        await page.waitForTimeout(100)
        assert.equal(await page.evaluate(() => window.marketScrollCalls.length), 0)
        await page.waitForTimeout(950)
        assert((await page.evaluate(() => window.marketScrollCalls[0].time)) - replacement >= 180)
        assert((await grid.boundingBox()).y >= (await header.boundingBox()).height - 1)
        const searchAfterScroll = await trigger('Open search').locator('..').boundingBox()
        const sortAfterScroll = await trigger('Sort').boundingBox()
        assert(Math.abs(searchAfterScroll.y - sortAfterScroll.y) < 1, 'Discover remains aligned after animated sticky scrolling')
        await pages.scrollIntoViewIfNeeded()
        await page.emulateMedia({ reducedMotion: 'reduce' })
        await page.evaluate(() => { window.marketScrollCalls = []; document.querySelector('[aria-label="Page 1"]').click() })
        await page.waitForTimeout(350)
        assert.equal(await page.evaluate(() => window.marketScrollCalls.length), 1, 'Reduced motion repositions once')
        await page.emulateMedia({ reducedMotion: 'no-preference' })
        await pages.getByRole('button', { name: 'Page 1', exact: true }).click(); await page.waitForTimeout(1300)
        await page.evaluate(() => { window.scrollTo = window.marketOriginalScrollTo; delete window.marketScrollCalls })
      }
      await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth))
      assert.deepEqual(errors, [])
      console.log(`PASS ${width}: solid sticky header, persistent card background, Glide drafts, blur exit, circular Profile, ${columns} columns and eased browsing`)
    }
  } finally { await browser.close() }
})().catch(e => { console.error(e); process.exitCode = 1 })
