/* global window, document */
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE)

;(async () => {
  const output = path.join(process.env.TEMP, 'profile-v1-checks')
  fs.mkdirSync(output, { recursive: true })
  const browser = await chromium.launch({ executablePath: process.env.BROWSER_EXECUTABLE,
    headless: true, ignoreDefaultArgs: ['--hide-scrollbars'], args: ['--enable-unsafe-swiftshader'] })
  try {
    for (const width of [390, 430, 1280, 1536]) {
      const page = await browser.newPage({ viewport: { width, height: 900 } })
      const errors = [], writes = []
      page.on('pageerror', error => errors.push(error.message))
      await page.route(/https:\/\/fonts\.(googleapis|gstatic)\.com\//, route => route.abort())
      await page.route('**/api/auth/session', route => route.fulfill({ json: { seller: { id: 'test', displayName: 'CampusMember' } } }))
      await page.route('**/api/profile/account', route => {
        if (route.request().method() !== 'GET') writes.push(route.request().method())
        return route.fulfill({ json: { username: 'CampusMember', email: 'member@uwo.ca', emailVerified: true, createdAt: '2026-10-01T12:00:00Z', nextUsernameChangeAt: null } })
      })
      await page.route('**/api/profile/categories', route => route.fulfill({ json: ['Electronics','Home & Dorm','Textbooks & School','Clothing & Accessories','Sports & Outdoors','Bikes & Mobility','Games & Hobbies','Other'].map((category, i) => ({ category, count: 80-i*9 })) }))
      await page.route('**/api/auth/username-availability?*', route => route.fulfill({ json: { available: false } }))
      await page.goto('http://localhost:3100/home', { waitUntil: 'domcontentloaded', timeout: 120000 })
      const root = page.locator('[data-slot="home-sidebar-demo"]')
      const desktop = width >= 1024
      const content = desktop ? root.locator('main').last() : root.locator('main').first()
      await content.getByText('member@uwo.ca', { exact: true }).waitFor()
      assert(await content.getByText('CampusMember', { exact: true }).isVisible())
      assert.equal(await content.getByLabel('Password hidden').textContent(), '\u2022'.repeat(8))
      assert(await content.getByText('Verified', { exact: true }).isVisible())
      if (desktop) {
        await content.locator('.recharts-area-curve').waitFor()
        await page.screenshot({ path: path.join(output, `${width}-profile.png`), fullPage: true })
      }
      assert(await content.getByText('October 2026', { exact: true }).isVisible())
      if (desktop) {
        const geometry = () => content.evaluate(el => ({ width: el.clientWidth, x: el.getBoundingClientRect().x, color: getComputedStyle(el).scrollbarColor }))
        const idle = await geometry()
        assert.equal(idle.color, 'rgba(0, 0, 0, 0) rgba(0, 0, 0, 0)')
        await content.hover()
        await page.waitForTimeout(250)
        assert.equal((await geometry()).color, idle.color, 'Hover does not reveal thumb')
        await page.mouse.wheel(0, 180)
        await page.waitForTimeout(180)
        assert.equal(await content.getAttribute('data-scrolling'), 'true')
        assert.notEqual((await geometry()).color, idle.color)
        await page.screenshot({ path: path.join(output, `${width}-scroll-active.png`) })
        await page.waitForTimeout(750)
        assert.equal(await content.getAttribute('data-scrolling'), null)
        assert.deepEqual(await geometry(), idle, 'Stable gutter and full hidden color after fade')
        await content.evaluate(el => { el.scrollTop = 0 })
        await page.waitForTimeout(850)
      }
      await content.getByRole('button', { name: 'Change', exact: true }).first().click()
      let dialog = page.getByRole('dialog', { name: 'Change username' })
      await dialog.waitFor()
      assert.equal(await dialog.getByLabel('Username').inputValue(), 'CampusMember')
      assert(await dialog.getByRole('button', { name: 'Save', exact: true }).isDisabled())
      await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
      await dialog.waitFor({ state: 'detached' })
      await content.getByRole('button', { name: 'Change', exact: true }).last().click()
      dialog = page.getByRole('dialog', { name: 'Change password' })
      assert.equal(await dialog.getByLabel('Current password', { exact: true }).inputValue(), '')
      assert.equal(await dialog.getByLabel('New password', { exact: true }).inputValue(), '')
      await dialog.getByLabel('New password', { exact: true }).fill('PASSWORD1!')
      assert.equal(await dialog.locator('li[data-met]').count(), 4, 'Existing four password rules; no lowercase added')
      await dialog.getByLabel('Confirm new password').fill('different')
      assert(await dialog.getByText('Passwords do not match.').isVisible())
      assert(await dialog.getByRole('button', { name: 'Save', exact: true }).isDisabled())
      await page.keyboard.press('Escape')
      await dialog.waitFor({ state: 'detached' })
      const selectChild = async name => {
        const menu = root.locator('[data-smooth-dropdown]')
        await menu.getByRole('button', { name: 'Show more', exact: true }).click()
        await menu.getByRole('button', { name, exact: true }).click()
        await page.waitForTimeout(300)
      }
      if (desktop) {
        assert(await content.getByRole('heading', { name: 'Profile', exact: true }).isVisible())
        assert.equal(await root.locator('[data-slot="sidebar"]').getByRole('button', { name: 'Analytics', exact: true }).count(), 0)
      } else {
        await page.screenshot({ path: path.join(output, `${width}-overview.png`), fullPage: true })
        const menu = root.locator('[data-smooth-dropdown]')
        await menu.getByRole('button', { name: 'Show more', exact: true }).click()
        assert(await menu.getByRole('button', { name: 'Overview', exact: true }).isVisible())
        assert(await menu.getByRole('button', { name: 'Analytics', exact: true }).isVisible())
        assert(await menu.getByRole('button', { name: 'Payment', exact: true }).isVisible())
        await menu.getByRole('button', { name: 'Analytics', exact: true }).click()
        await page.waitForTimeout(300)
        assert(await content.getByRole('heading', { name: 'Analytics', exact: true }).isVisible())
      }
      const trend = content.getByRole('region', { name: 'Your Activity', exact: true })
      const performance = content.getByRole('region', { name: 'Marketplace Trends', exact: true })
      await trend.locator('.recharts-area-curve').waitFor()
      await performance.locator('.recharts-bar-rectangle').first().waitFor()
      const trendBox = await trend.boundingBox(), barBox = await performance.boundingBox()
      if (desktop) {
        assert(Math.abs(trendBox.y - barBox.y) < 1)
        assert(trendBox.x + trendBox.width < barBox.x)
        const overview = await content.getByRole('region', { name: 'Overview', exact: true }).boundingBox()
        assert(overview.y + overview.height < trendBox.y)
        assert(Math.abs(overview.width - trendBox.width - barBox.width - 20) < 1)
      } else {
        assert(barBox.y >= trendBox.y + trendBox.height + 19)
        assert(Math.abs(trendBox.x - barBox.x) < 1)
        assert(Math.abs(trendBox.width - ((await page.evaluate(() => document.documentElement.clientWidth)) - 48)) < 1)
        assert(Math.abs(trendBox.width - barBox.width) < 1)
      }
      assert.equal(await performance.getAttribute('data-category-layout'), 'vertical')
      const bars = await performance.locator('.recharts-bar-rectangle').evaluateAll(nodes => nodes.map(node => {
        const r = node.getBoundingClientRect(); return { width: r.width, height: r.height }
      }))
      assert.equal(bars.length, 8)
      assert(bars[0].width > bars[0].height, 'Actual bars are horizontal')
      assert(bars.every((bar, index) => !index || bar.width < bars[index - 1].width), 'Views descending')
      const curve = () => trend.locator('.recharts-area-curve').getAttribute('d')
      const before = await curve()
      await trend.getByRole('button', { name: 'Sold', exact: true }).click()
      assert.notEqual(await curve(), before, 'Metric changes actual chart geometry')
      await trend.getByRole('button', { name: '1D', exact: true }).click()
      assert.equal(await trend.locator('[data-trend-points]').getAttribute('data-trend-points'), '24')
      await trend.getByRole('button', { name: '30D', exact: true }).click()
      assert.equal(await trend.locator('[data-trend-points]').getAttribute('data-trend-points'), '30')
      await trend.getByRole('button', { name: '7D', exact: true }).click()
      const unchanged = await curve()
      await performance.locator('.recharts-bar-rectangle').first().click()
      assert.equal(await curve(), unchanged, 'Category bars never change personal activity')
      assert.equal(await trend.locator('[data-trend-listing]').getAttribute('data-trend-listing'), 'account')
      await page.screenshot({ path: path.join(output, `${width}-analytics.png`), fullPage: true })
      if (!desktop) {
        await selectChild('Payment')
        assert(await content.getByRole('heading', { name: 'Payment', exact: true }).isVisible())
        assert(await content.getByText('Coming later', { exact: true }).isVisible())
        assert.equal(await content.locator('[data-chart]').count(), 0)
      }
      assert(await root.evaluate(el => el.getBoundingClientRect().height >= el.scrollHeight - 1), 'Home background covers its natural mobile content height')
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth))
      assert.deepEqual(writes, [])
      assert.deepEqual(errors, [])
      console.log(`PASS ${width}: responsive Profile, chart metric/period updates and independent category counts, safe account dialogs, mock labels, no overflow/errors/writes`)
      await page.close()
    }
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
